### ISSUE TITLE
Published service undiscoverable due to NSEC

### ISSUE THREAD

**Issue by bbusse** [python-zeroconf/python-zeroconf#1088]
There is a problem when trying to discover a service published by python-zeroconf with https://github.com/grandcat/zeroconf/ See also: https://github.com/grandcat/zeroconf/issues/34 Leaving out the NSEC block in python-zeroconf, e.g. not sending it at all, makes the discovery work with the golang side

**Comment by bdraco** [comment]
Looks like a bug in https://github.com/jstasiak/python-zeroconf/blob/60167b05227ec33668aac5b960a8bc5ba5b833de/zeroconf/_dns.py#L474

Unfortunately, I don't see the problem, but happy to take a patch if you can work out whats wrong.
