### ISSUE TITLE
Make it work with Python 3.6 as it is LTS in RedHat

### ISSUE THREAD

**Issue by petrkr** [python-zeroconf/python-zeroconf#1104]
How to make to work this package with Python 3.6?

I need to use this with Rocky Linux / CentOS / RHEL 8 which have support up to 2029.
Python 3.7+ have support only up to 2023 (2024 resp), but Python 3.6 up to 2029... I can not do production-grade system on unsupported platform or some workarounds.

Thanks for any production-grade suggest.

https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle#rhel8_application_streams

**Comment by bdraco** [comment]
You'll need to use [0.37.0](https://github.com/python-zeroconf/python-zeroconf/releases/tag/0.37.0) for older pythons
