### ISSUE TITLE
`parsed_scoped_addresses` does not return with `scope_id`

### ISSUE THREAD

**Issue by netanelc305** [python-zeroconf/python-zeroconf#1288]
I run the example [`browse.py`](https://github.com/python-zeroconf/python-zeroconf/blob/master/examples/browser.py), And I am listening only on ipv6.  The addresses return from `parsed_scoped_addresses` missing the `scope_id`. 
How can I fix it?

**Comment by bdraco** [comment]
Looks like a bug. Working on a fix in https://github.com/python-zeroconf/python-zeroconf/pull/1322
