### ISSUE TITLE
pip install zeroconf stuck buidling wheel

### ISSUE THREAD

**Issue by alestiago** [python-zeroconf/python-zeroconf#1319]
When installing `zeroconf` using:

```sh
pip install zeroconf
```

It gets stuck on "Building wheel for zeroconf (pyproject.toml)"

```txt
Collecting zeroconf
  Using cached zeroconf-0.128.0.tar.gz (161 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting async-timeout>=3.0.0 (from zeroconf)
  Using cached async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting ifaddr>=0.1.7 (from zeroconf)
  Using cached ifaddr-0.2.0-py3-none-any.whl (12 kB)
Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Building wheels for collected packages: zeroconf
  Building wheel for zeroconf (pyproject.toml) ... |
```

Running on pip 23.3.1 and Python 3.8.18 with MacOs (arm)

**Comment by bdraco** [comment]
Have you tried installing with `pip install -vvv zeroconf` to see where its stuck?

**Comment by aoyurs** [comment]
I had the same problem
`
Building wheels for collected packages: zeroconf
  Created temporary directory: /tmp/pip-wheel-cprkllq1
  Destination directory: /tmp/pip-wheel-cprkllq1
  Running command Building wheel for zeroconf (pyproject.toml)
  fatal: not a git repository (or any of the parent directories): .git
  A setup.py file already exists. Using it.
`

**Comment by bdraco** [comment]
If your compiler is broken you can install with 

`export SKIP_CYTHON=1`

**Comment by alestiago** [comment]
It seems that building the wheel takes a longer than expected amount of time. After doing a very verbose install (`pip install -vvv zeroconf`) it did build the wheel.

Although during the installation multiple warnings were thrown, such as:
```txt
  src/zeroconf/_dns.c:54778:21: warning: fallthrough annotation in unreachable code [-Wunreachable-code-fallthrough]
                      CYTHON_FALLTHROUGH;
                      ^
```

it did, regardless, exit successfully with:
```txt
Successfully installed ifaddr-0.2.0 zeroconf-0.131.0
```

**Comment by bdraco** [comment]
Looks like it boils down to the host system being slow.

Which arch and python version are you using? Maybe we can build wheels for that system so you don't have to build them locally.

**Comment by aoyurs** [comment]
It seems to have nothing to do with the python version. I used anaconda to switch to several versions, but the same thing happened, 3.7, 3.8, etc. I used Raspberry Pi 4B, aarch64. But give it enough time and it does install successfully.

**Comment by alestiago** [comment]
@bdraco the Python version I was using was 3.9.13, managed by conda. The OS was a macOS Sonoma 14.1 running on a Apple M1 chip.

**Comment by bdraco** [comment]
We currently don't build any wheels for Apple silicon. 

Cibuildwheel does support it though so if you want to send a PR it's something we could add 

https://cibuildwheel.readthedocs.io/en/stable/faq/

**Comment by Arksine** [comment]
Some of my project's users are running into the same issue, as its primarily run on arm/mips based SBCs.  Would you consider adding a pure python wheel to to pypi?  This would provide a binary fallback for all platforms without cython builds.  It also skips installing the build dependencies which speeds up installation on slower machines.

I took a look at your workflow and came up with the following additional step to add a pure wheel:
```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index da9db34..624eabe 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -162,6 +162,15 @@ jobs:
           CIBW_BUILD_VERBOSITY: 3
           REQUIRE_CYTHON: 1
 
+      - name: Build pure wheel
+        if: runner.os == 'Linux'
+        run: |
+          pip install build
+          cp pyproject.toml pyproject.toml.bak
+          sed -i -E -e '/\[tool.poetry.build\]/,/^$/d' pyproject.toml
+          python -m build --wheel --outdir ./wheelhouse .
+          mv pyproject.toml.bak pyproject.toml
+
       - uses: actions/upload-artifact@v3
         with:
           path: ./wheelhouse/*.whl
```

Since poetry doesn't have a clean way of disabling the c extension this step just strips out the `[tool.poetry.build]` section from `pyproject.toml` prior to the build. If you are interested I would be more than happy to provide a pull request.  Thanks.

**Comment by bdraco** [comment]
I'd rather not publish a pure python wheel because it will be a breaking change in behavior and cause systems to always prefer the pure python one when a prebuilt one is not available instead of trying to build it which may be a major performance problem for those systems at run time.

**Comment by bdraco** [comment]
Instead it would be better to add new CI jobs to build wheels with QEMU for the platforms that need it.

**Comment by bdraco** [comment]
Also if you are using RPI 32bit, piwheels already builds them https://www.piwheels.org/project/zeroconf/

**Comment by bdraco** [comment]
Also we are already building some aarch64 wheels https://pypi.org/project/zeroconf/#files

If you need other ones it would probably be fine to split the CI jobs with a matrix and add a few more
```
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]
        platforms: ["auto", "aarch64", "...."]
```
