### ISSUE TITLE
Best way to be notified when a service disappears?

### ISSUE THREAD

**Issue by tomkcook** [python-zeroconf/python-zeroconf#1362]
Is there a good way to be notified when a service disappears without calling `unregister_service()`?  Or do I have to regularly check that the service is still responding as advertised and manually discard my old record for it?

**Comment by bdraco** [comment]
Here is a production use case of a remove listener
https://github.com/home-assistant/core/blob/ab29718a455ed6c625a0459400c816f293e695b8/homeassistant/components/zeroconf/__init__.py#L411

If you need something on demand:

https://github.com/Jc2k/aiohomekit/blob/29b77e72d391d4bf0f4a3a0b17fe6ce0d2047f77/aiohomekit/zeroconf.py#L330
