### ISSUE TITLE
Incomplete PyPi Release Assets

### ISSUE THREAD

**Issue by shauneccles** [python-zeroconf/python-zeroconf#1368]
Hi,

Looks like the CI has failed during the release process - PyPi only has the sdist and a single py310 wheel.

![image](https://github.com/python-zeroconf/python-zeroconf/assets/21007065/c0d3604f-938f-4693-842f-f9acc5da3542)

https://github.com/python-zeroconf/python-zeroconf/actions/runs/8512848710

**Comment by kpfleming** [comment]
Indeed, my fairly slow machine that runs HA is currently building a `zeroconf` wheel since none could be found on PyPI.
