### ISSUE TITLE
AssertionError in _services/info.py

### ISSUE THREAD

**Issue by elibroftw** [python-zeroconf/python-zeroconf#1374]
I'm not sure what's going on but with both v13 and v14 of pychromecast, there are some serious degradations with the use of pyzeroconf.

https://github.com/home-assistant-libs/pychromecast/issues/866
https://github.com/home-assistant-libs/pychromecast/issues/897

I suggest that the `assert zc.loop is not None and zc.loop.is_running()` be split into two assertions since the exception does not specify which of the two conditionals failed the assertion.

**Comment by bdraco** [comment]
Its likely you are trying to use zeroconf after its stopped
