### ISSUE TITLE
Build ARM64 wheel for macOS

### ISSUE THREAD

**Issue by cbrnr** [python-zeroconf/python-zeroconf#1376]
Would it be possible to provide a wheel for `macOS-arm64`? This might be as easy as using the `-latest` images [here](https://github.com/python-zeroconf/python-zeroconf/blob/master/.github/workflows/ci.yml#L129), because `macOS-latest` (aka `macOS-14`) should produce a universal wheel for both architectures.

**Comment by bdraco** [comment]
https://github.com/python-zeroconf/python-zeroconf/pull/1384
