### ISSUE TITLE
Missing wheels for macOS running on Apple Silicon (M1+)

### ISSUE THREAD

**Issue by doronz88** [python-zeroconf/python-zeroconf#1380]
Hi,

zeroconf installation on Apple Silicon is very slow. I noticed your CI deploys all the required intel-based wheels, but non of the AARCH64. From my understanding, you can simply fix that by removing the aarch64 flavors from `CIBW_SKIP`.

Is there any praticular reason why that is done in the first place?

**Comment by bdraco** [comment]
The builds were failing because they took longer than 6 hours

It needs to be split up into multiple jobs to avoid hitting the github limit.

I was hoping cython 3.1 would come out sooner which is expected to speed up compiles and remove the need to split it to achieve that

**Comment by doronz88** [comment]
Why is that? sounds like a bug. Could you verify this still occurs because I have no problems building mac arm wheels on github CI

**Comment by bdraco** [comment]
https://github.com/python-zeroconf/python-zeroconf/pull/1384
