### ISSUE TITLE
Allow substring/regexp in ServiceBrowser service type

### ISSUE THREAD

**Issue by esazhin** [python-zeroconf/python-zeroconf#14]
It would be nice to add an ability to create a service browser using a substring of service type. This way one could create a set of custom services with types like this:

_mygroup._bob._tcp.
_mygroup._bob1._tcp.
_mygroup._alice._tcp.

So that the discovery would return 
all three for "_mygroup._"
only two for "_bob_" or for "_mygroup._bob*"
ad only one for "alice" or "bob1" 

This would allow for comprehensive managements of services of different types, while allowing to filter out something that is not interesting for particular browser.

**Comment by jstasiak** [comment]
Hey, I meant to respond to this ticket but forgot; this is something I'd like to have, can't promise anything though.

**Comment by bdraco** [comment]
ServiceBrowsers have supported multiple types for long time now.
