### ISSUE TITLE
Registration of name which is not of correct type is feasible

### ISSUE THREAD

**Issue by mattsaxon** [python-zeroconf/python-zeroconf#167]
The test:
`def test_integration_with_listener_class(self):`

registers the service of name "xxxyyyæøå._http._tcp.local." with type "My special Subtype._http._tcp.local.

This should be invalid, but the test passes. The fix to this is fairly trivial, but fixing this may be a breaking change if people have used this facility.

**Comment by bdraco** [comment]
At some point we changed this and there was a guard added to ServiceInfo to prevent this
