### ISSUE TITLE
Registration of a single listener for multiple types is not possible

### ISSUE THREAD

**Issue by mattsaxon** [python-zeroconf/python-zeroconf#168]
Consider the test

```
zeroconf_browser.add_service_listener(type, listener)
zeroconf_browser.add_service_listener(subtype, listener)
```
This codes is valid and executes, however the type listener becomes unregistered and only subtype listens.

I found this when creating the test 
`def test_integration_with_listener_class_with_update(self):`

This was unexpected. I would have expected an exception or for listener to be called with events from either type.

**Comment by bdraco** [comment]
This has been fixed for a while, but its more efficient to create a `ServiceBrowser` with both types instead of starting two of them via this method
