### ISSUE TITLE
zeroconf.BadTypeInNameException: Ascii control character 0x00-0x1F and 0x7F illegal

### ISSUE THREAD

**Issue by jvitkauskas** [python-zeroconf/python-zeroconf#306]
I have a device this seems to have a name followed by CR and LF which python-zeroconf does not allow

```
zeroconf.BadTypeInNameException: Ascii control character 0x00-0x1F and 0x7F illegal in 'Gateway_00:1e:5e:92:00:ac
'
```

any chance I could get this working? Maybe this could be changed to a warning instead of exception?

**Comment by jstasiak** [comment]
Please provide the relevant details:
* OS version
* Python version
* python-zeroconf version
* What are you doing (registering a service, browsing services etc.) – a sample piece of code would be nice
* Full stack trace (just the exception is rarely enough)

**Comment by bdraco** [comment]
@jvitkauskas Is this still an issue on `upstream/master`?

**Comment by bdraco** [comment]
closing due to lack of response
