### ISSUE TITLE
Add some release automation

### ISSUE THREAD

**Issue by jstasiak** [python-zeroconf/python-zeroconf#355]
This seems useful: https://github.com/marketplace/actions/release-drafter (@bdraco suggested this and I like the idea)

**Comment by bdraco** [comment]
Support for `bump2version` has been added. I'm not 100% sure the best approach to drafting the release notes in the existing format is as they need to end up in README.rst.  Something to think about.

**Comment by bdraco** [comment]
Looks like I should add a publish workflow to the CI so I don't screw up the directory permissions again as reported in https://github.com/jstasiak/python-zeroconf/issues/923

**Comment by bdraco** [comment]
release automation is now in place
